name: Deploy Vue

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check Node Version
        run: node -v

      - name: Install
        run: npm install

      - name: Build
        run: npm run build


        # --- TAMBAHKAN BAGIAN INI DI BAWAHNYA ---
      - name: 📂 Sync files to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          
          # Folder hasil build (Vue biasanya 'dist')
          local-dir: ./dist/
          
          # Taruh di public_html
          server-dir: /public_html/
          
          # PENTING: Lindungi Backend biar gak kehapus
          exclude: |
            apikodyakost/**
            apikodyakost