name: Deploy Vue

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check Node Version
        run: node -v

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
